# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pgw.proto import vehicle_pb2 as pgw_dot_proto_dot_vehicle__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pgw/proto/vehicle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VehicleServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVehicleState = channel.unary_unary(
                '/pgw.vehicle.v1.VehicleService/GetVehicleState',
                request_serializer=pgw_dot_proto_dot_vehicle__pb2.GetVehicleStateRequest.SerializeToString,
                response_deserializer=pgw_dot_proto_dot_vehicle__pb2.VehicleState.FromString,
                _registered_method=True)
        self.SendCommand = channel.unary_unary(
                '/pgw.vehicle.v1.VehicleService/SendCommand',
                request_serializer=pgw_dot_proto_dot_vehicle__pb2.SendCommandRequest.SerializeToString,
                response_deserializer=pgw_dot_proto_dot_vehicle__pb2.SendCommandResponse.FromString,
                _registered_method=True)


class VehicleServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetVehicleState(self, request, context):
        """Latest known state of one vehicle, as last reported by the car.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommand(self, request, context):
        """Queue a command for a vehicle. Returns as soon as the command is accepted;
        the car's result arrives later as an event on the `vehicle-command-results` topic.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVehicleState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleState,
                    request_deserializer=pgw_dot_proto_dot_vehicle__pb2.GetVehicleStateRequest.FromString,
                    response_serializer=pgw_dot_proto_dot_vehicle__pb2.VehicleState.SerializeToString,
            ),
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=pgw_dot_proto_dot_vehicle__pb2.SendCommandRequest.FromString,
                    response_serializer=pgw_dot_proto_dot_vehicle__pb2.SendCommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pgw.vehicle.v1.VehicleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pgw.vehicle.v1.VehicleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehicleService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVehicleState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pgw.vehicle.v1.VehicleService/GetVehicleState',
            pgw_dot_proto_dot_vehicle__pb2.GetVehicleStateRequest.SerializeToString,
            pgw_dot_proto_dot_vehicle__pb2.VehicleState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pgw.vehicle.v1.VehicleService/SendCommand',
            pgw_dot_proto_dot_vehicle__pb2.SendCommandRequest.SerializeToString,
            pgw_dot_proto_dot_vehicle__pb2.SendCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
