# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pgw/proto/vehicle.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pgw/proto/vehicle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17pgw/proto/vehicle.proto\x12\x0epgw.vehicle.v1\"%\n\x16GetVehicleStateRequest\x12\x0b\n\x03vin\x18\x01 \x01(\t\"\xa3\x01\n\x0cVehicleState\x12\x0b\n\x03vin\x18\x01 \x01(\t\x12\x0e\n\x06online\x18\x02 \x01(\x08\x12\x0e\n\x06locked\x18\x03 \x01(\x08\x12\x17\n\x0f\x62\x61ttery_percent\x18\x04 \x01(\x05\x12\x13\n\x0bodometer_km\x18\x05 \x01(\x01\x12\x10\n\x08latitude\x18\x06 \x01(\x01\x12\x11\n\tlongitude\x18\x07 \x01(\x01\x12\x13\n\x0breported_at\x18\x08 \x01(\t\"t\n\x12SendCommandRequest\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12)\n\x04type\x18\x03 \x01(\x0e\x32\x1b.pgw.vehicle.v1.CommandType\x12\x12\n\npartner_id\x18\x04 \x01(\t\"N\n\x13SendCommandResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x11\n\tduplicate\x18\x03 \x01(\x08*|\n\x0b\x43ommandType\x12\x1c\n\x18\x43OMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04LOCK\x10\x01\x12\n\n\x06UNLOCK\x10\x02\x12\x12\n\x0eSTART_CHARGING\x10\x03\x12\x11\n\rSTOP_CHARGING\x10\x04\x12\x12\n\x0eHONK_AND_FLASH\x10\x05\x32\xc1\x01\n\x0eVehicleService\x12W\n\x0fGetVehicleState\x12&.pgw.vehicle.v1.GetVehicleStateRequest\x1a\x1c.pgw.vehicle.v1.VehicleState\x12V\n\x0bSendCommand\x12\".pgw.vehicle.v1.SendCommandRequest\x1a#.pgw.vehicle.v1.SendCommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pgw.proto.vehicle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDTYPE']._serialized_start=446
  _globals['_COMMANDTYPE']._serialized_end=570
  _globals['_GETVEHICLESTATEREQUEST']._serialized_start=43
  _globals['_GETVEHICLESTATEREQUEST']._serialized_end=80
  _globals['_VEHICLESTATE']._serialized_start=83
  _globals['_VEHICLESTATE']._serialized_end=246
  _globals['_SENDCOMMANDREQUEST']._serialized_start=248
  _globals['_SENDCOMMANDREQUEST']._serialized_end=364
  _globals['_SENDCOMMANDRESPONSE']._serialized_start=366
  _globals['_SENDCOMMANDRESPONSE']._serialized_end=444
  _globals['_VEHICLESERVICE']._serialized_start=573
  _globals['_VEHICLESERVICE']._serialized_end=766
# @@protoc_insertion_point(module_scope)
